### ISSUE TITLE
RSS?

### ISSUE THREAD

**Issue by simshadows** [cjdb/cjdb.github.io#3]
Getting an RSS feed on your blog by any chance? I'd love to stay subscribed to it ;P

**Comment by cjdb** [comment]
Brilliant idea! I'll look into how to do it between now and just before the next publiation 😄 .

**Comment by swarupsahoo** [comment]
Yes, RSS please.

**Comment by cjdb** [comment]
RSS feed now available: https://www.cjdb.com.au/feed.xml

**Comment by mpoullet** [comment]
Works perfectly well with Feedly, thanks!

**Comment by swarupsahoo** [comment]
Thanks.
