### ISSUE TITLE
Mixed Content Security 

### ISSUE THREAD

**Issue by jseba** [cjdb/cjdb.github.io#4]
The mixed use of HTTPS and HTTP is causing browsers to flag the site transition from http://cjdb.com.au/blog to https://github.com/cjdb/cjdb.github.io/issues as insecure. Looking at the source code for the cjdb.com.au/blog page, it looks like you're trying to load the GitHub Pages site as an iframe. The change from insecure frame contents to secure frame contents is what is the problem (I think).

I think there are two or three possible solutions. One would be to get SSL set up on your domain using Let's Encrypt so that there is no transition from insecure to secure. I think this step should be done regardless, as plain HTTP is being deprecated everywhere and Google is even ranking insecure pages lower.

You could also use a subdomain instead of a subdirectory (blog.cjdb.com.au as opposed to cjdb.com.au/blog). With this, you can just set the subdomain to resolve to the GitHub Pages site. See https://help.github.com/articles/setting-up-an-apex-domain. This has the benefit of not requiring a web server to manage the proxy over to GH Pages, so you only have to pay for the domain and not a full server as well.

The last one would be, instead of using an iframe, to set up /blog/ to forward to the cjdb.github.io directly. I'm not sure if you're using Apache or ngnix as your web server, but it should be straightforward to set that up. This is the more involved of the two, but has the benefit of keeping your links intact, which the subdomain does not, as well as keeping a web server active to service any other sites besides just managing the proxy.

**Comment by cjdb** [comment]
I think this issue has been resolved, can you please confirm?

**Comment by jseba** [comment]
I can indeed confirm, both Firefox and Edge are happy now!
